version: '3.9'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_USERNAME=app
      - DB_PASSWORD=prueba
      - DB_PORT=3306
      - DB_NAME=app
      - DB_SERVER=db
      - TRACKER_BASE_URL=https://public-api.tracker.gg/v2/division-2/standard
      - TRACKER_API_KEY=
      - NODE_ENV=dev
  db:
    image: mysql:5.7
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=prueba
      - MYSQL_ROOT_PASSWORD=prueba
      - MYSQL_DATABASE=app
